name: AMV Travel QA Suite

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar Test Web AMV
        env:
          AMV_USER: ${{ secrets.AMV_USER }}
          AMV_PASS: ${{ secrets.AMV_PASS }}

        run: |
          pytest inicio/login.py inicio/hoteles.py inicio/servicios.py inicio/ofertas.py tarifario/paquetes.py tarifario/excursiones.py --alluredir=allure-results || true

      - name: Generar carpeta con Fecha y Hora
        run: |
          echo "REPORT_DATE=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

      - name: Generar Reporte Allure
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_histories: 1

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
